//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_dot_net
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetail
    {
        public int ID { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public bool IsPermanent { get; set; }
        public Nullable<long> StudentID { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
