<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Day_6_ADO_2.aspx.cs" Inherits="Learning_dot_net.Day_6_ADO_2" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <h2>Student</h2>
    <div class="row">
        <div class="form-group">
            <asp:Label ID="lblName" CssClass="form-label col-md-4 text-right" runat="server" Text="Name"></asp:Label>
            <asp:TextBox ID="txtName" CssClass="form-control col-md-8" runat="server"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" ControlToValidate="txtName" CssClass="text-danger" runat="server" ErrorMessage="Name Required"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group">
            <asp:Label ID="lblFatherName" CssClass="form-label col-md-4 text-right" runat="server" Text="Father's Name"></asp:Label>
            <asp:TextBox ID="txtFatherName" CssClass="form-control col-md-8" runat="server"></asp:TextBox>
        </div>

        <div class="form-group">
            <asp:Label ID="lblMobile" CssClass="form-label col-md-4 text-right" runat="server" Text="Mobile Number"></asp:Label>
            <asp:TextBox ID="txtMobile" CssClass="form-control col-md-8" runat="server"></asp:TextBox>
        </div>
        <div class="form-group">
            <asp:Label ID="lblDob" CssClass="form-label col-md-4 text-right" runat="server" Text="Date of Birth"></asp:Label>
            <asp:TextBox ID="txtDateOfBirth" CssClass="form-control col-md-8" runat="server"></asp:TextBox>
        </div>

        <div class="form-group text-center"> 
            <asp:Button ID="btnCancel" CssClass="btn btn-danger" runat="server" Text="Cancel" OnClick="btnCancel_Click" />
            <asp:Button ID="btnSave" CssClass="btn btn-success" runat="server" Text="Save" OnClick="btnSave_Click" />
            <br />
            <asp:Label ID="lblMessage" CssClass="text-success" runat="server" Text=""></asp:Label>
        </div>
    </div>
    <div class="row">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing">
            <Columns> 
                <asp:TemplateField HeaderText="Name">
                    <ItemTemplate>
                        <%#Eval("Name") %>
                    </ItemTemplate>
                </asp:TemplateField>
                 <asp:TemplateField HeaderText="Father's Name">
                    <ItemTemplate>
                        <%#Eval("FatherName") %>
                    </ItemTemplate>
                </asp:TemplateField>
            <asp:BoundField HeaderText="Mobile" DataField="Mobile" />
             </Columns>
        </asp:GridView>
    </div>
</asp:Content>
